"""Compile a validated graph into deterministic GitHub Actions files."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, replace
from pathlib import PurePosixPath
from typing import TYPE_CHECKING, cast, override

import yaml

from quality_graph_core.graph import (
    DependencyPolicy,
    Flow,
    FlowNode,
    Graph,
    LabelSpec,
    Node,
    Profile,
    Step,
)
from quality_graph_core.provider import GeneratedFile, GeneratedProject

if TYPE_CHECKING:
    from collections.abc import Mapping

    from quality_graph_core.result import JsonValue

GENERATED_NOTICE = (
    "Generated by Quality Graph. DO NOT EDIT MANUALLY. Update qg.yaml and run qg generate."
)
GENERATED_HEADER = f"# {GENERATED_NOTICE}\n---\n"
EXECUTION_WORKFLOW = PurePosixPath(".github/workflows/quality-graph.yml")
PUSH_WORKFLOW = PurePosixPath(".github/workflows/quality-graph-push.yml")
PUBLICATION_WORKFLOW = PurePosixPath(".github/workflows/quality-graph-publish.yml")
GRAPH_MANIFEST = PurePosixPath(".quality-graph/manifest.json")
DEFAULT_UPLOAD_ARTIFACT_ACTION = "actions/upload-artifact@v7"
ACTION_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)?@[A-Za-z0-9_.:/-]+$")
RUNTIME_ACTION_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+@[0-9a-f]{40}$")
PERMISSION_NAMES = {
    "actions",
    "checks",
    "contents",
    "deployments",
    "discussions",
    "id-token",
    "issues",
    "packages",
    "pages",
    "pull-requests",
    "repository-projects",
    "security-events",
    "statuses",
}
INVALID_BRANCH_CHARACTER_RE = re.compile(r"[\x00-\x20\x7f ~^:?*\[\\]")
MAX_BRANCH_NAME_LENGTH = 255
SUPPORTED_EVENTS = ("pull-request", "push")


@dataclass(frozen=True)
class EventProjection:
    """Carry one provider-validated event projection into workflow generation."""

    event: str
    nodes: tuple[Node, ...]
    dependencies: DependencyPolicy


@dataclass(frozen=True)
class _GitHubConfiguration:
    runtime_action: str
    publisher_action: str
    upload_artifact_action: str
    default_branch: str
    merge_required: bool


class WorkflowDumper(yaml.SafeDumper):
    """Render deterministic YAML without aliases for shared immutable values."""

    @override
    def ignore_aliases(self, _data: object) -> bool:
        """Keep generated workflows locally readable."""
        return True

    @override
    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        del indentless
        super().increase_indent(flow, indentless=False)


def _validate_github_graph(graph: Graph) -> _GitHubConfiguration:
    if graph.provider.name != "github":
        message = f"GitHub provider cannot compile provider '{graph.provider.name}'"
        raise ValueError(message)
    unknown = graph.provider.values.keys() - {"default-branch", "runtime", "merge"}
    if unknown:
        message = f"GitHub provider contains unknown configuration: {', '.join(sorted(unknown))}"
        raise ValueError(message)
    runtime = graph.provider.values.get("runtime")
    if not isinstance(runtime, dict):
        message = "GitHub provider requires a runtime object"
        raise TypeError(message)
    if runtime.keys() - {"action", "publisher-action", "upload-artifact-action"}:
        message = "GitHub runtime contains unknown fields"
        raise ValueError(message)
    action = _runtime_action(runtime.get("action"), "runtime")
    publisher_action = _runtime_action(runtime.get("publisher-action", action), "publisher")
    upload_artifact_action = _upload_artifact_action(runtime)
    default_branch = _default_branch(graph.provider.values.get("default-branch"))
    merge_required = _merge_required(graph.provider.values.get("merge", {}))
    if publisher_action.partition("@")[0] != action.partition("@")[0]:
        message = "GitHub publisher action must use the runtime action repository"
        raise ValueError(message)
    _validate_execution_contracts(graph)
    if graph.flows:
        _validate_explicit_flows(graph)
        _validate_merge_presentation(graph, merge_required=merge_required)
    else:
        _event_projections(graph)
    return _GitHubConfiguration(
        action,
        publisher_action,
        upload_artifact_action,
        default_branch,
        merge_required,
    )


def _validate_execution_contracts(graph: Graph) -> None:
    if graph.flow_id is not None:
        message = "compile the original declaration, not a resolved flow"
        raise ValueError(message)
    for profile in graph.profiles:
        _validate_permissions(profile)
        for step in profile.setup:
            _validate_step(step)
    for node in graph.nodes:
        _validate_step(node.step)
    for operation in graph.operations:
        _validate_step(operation.step)
    titles = [node.title for node in graph.nodes]
    if len(set(titles)) != len(titles):
        message = "GitHub dashboard requires unique node titles"
        raise ValueError(message)


def _validate_merge_presentation(graph: Graph, *, merge_required: bool) -> None:
    if merge_required and not any(flow.presentation == "github-pr" for flow in graph.flows):
        message = "merge.required needs an enabled GitHub PR presentation adapter"
        raise ValueError(message)


def _merge_required(merge: JsonValue) -> bool:
    if not isinstance(merge, dict):
        message = "GitHub merge configuration must be an object"
        raise TypeError(message)
    if merge.keys() - {"required"}:
        message = "GitHub merge configuration contains unknown fields"
        raise ValueError(message)
    merge_required = merge.get("required", False)
    if not isinstance(merge_required, bool):
        message = "GitHub merge required must be a boolean"
        raise TypeError(message)
    return merge_required


def _event_projections(graph: Graph) -> tuple[EventProjection, ...]:
    if graph.flows:
        return tuple(
            EventProjection(
                "push" if flow.trigger == "push" else "pull-request",
                graph.for_flow(flow.id).nodes,
                flow.dependencies,
            )
            for flow in graph.flows
            if flow.trigger != "workflow-dispatch"
        )
    supported = set(SUPPORTED_EVENTS)
    unknown = set(graph.execution) - supported
    for node in graph.nodes:
        unknown.update(set(node.events) - supported)
    if unknown:
        names = ", ".join(sorted(unknown))
        message = f"GitHub provider contains unsupported execution events: {names}"
        raise ValueError(message)
    projections: list[EventProjection] = []
    for event in SUPPORTED_EVENTS:
        nodes = tuple(node for node in graph.nodes if not node.events or event in node.events)
        if not nodes:
            message = f"GitHub {event} event projection must contain at least one node"
            raise ValueError(message)
        dependency_policy = graph.execution.get(event, DependencyPolicy.GRAPH)
        if dependency_policy is DependencyPolicy.GRAPH:
            selected = {node.id for node in nodes}
            for node in nodes:
                missing = set(node.needs) - selected
                if missing:
                    message = (
                        f"GitHub {event} event projection excludes dependencies of {node.id}: "
                        f"{', '.join(sorted(missing))}"
                    )
                    raise ValueError(message)
        else:
            nodes = tuple(replace(node, needs=()) for node in nodes)
        projections.append(EventProjection(event, nodes, dependency_policy))
    return tuple(projections)


def event_projection(graph: Graph, event: str) -> EventProjection:
    """Return one validated GitHub event projection."""
    for projection in _event_projections(graph):
        if projection.event == event:
            return projection
    message = f"GitHub provider does not support execution event: {event}"
    raise ValueError(message)


def project_graph(graph: Graph, event: str) -> Graph:
    """Return one dependency-normalized GitHub event graph."""
    if graph.flows:
        for flow in graph.flows:
            if flow.trigger == event:
                return graph.for_flow(flow.id)
        message = f"no flow declares the {event} trigger"
        raise ValueError(message)
    return replace(graph, nodes=event_projection(graph, event).nodes)


def _validate_explicit_flows(graph: Graph) -> None:
    for trigger in SUPPORTED_EVENTS:
        selected = [flow for flow in graph.flows if flow.trigger == trigger]
        if len(selected) > 1:
            message = f"GitHub supports one {trigger} flow per declaration"
            raise ValueError(message)
    for flow in graph.flows:
        for branch in flow.branches:
            _default_branch(branch)
        if flow.presentation == "github-pr":
            titles = [node.title for node in graph.for_flow(flow.id).nodes]
            if len(set(titles)) != len(titles):
                message = "GitHub PR presentation requires unique placement titles"
                raise ValueError(message)


def _default_branch(value: JsonValue) -> str:
    branch = "main" if value is None else value
    if not isinstance(branch, str) or not 1 <= len(branch) <= MAX_BRANCH_NAME_LENGTH:
        message = "GitHub default branch must be a non-empty string of at most 255 characters"
        raise ValueError(message)
    parts = branch.split("/")
    invalid = (
        branch in {"@", "HEAD"}
        or branch.startswith(("-", "!"))
        or branch.endswith(("/", "."))
        or "//" in branch
        or ".." in branch
        or "@{" in branch
        or INVALID_BRANCH_CHARACTER_RE.search(branch) is not None
        or any(not part or part.startswith(".") or part.endswith(".lock") for part in parts)
    )
    if invalid:
        message = f"GitHub default branch is invalid: {branch}"
        raise ValueError(message)
    return branch


def _runtime_action(value: JsonValue, context: str) -> str:
    if not isinstance(value, str) or RUNTIME_ACTION_RE.fullmatch(value) is None:
        message = f"GitHub {context} action must use owner/repository@40-character-commit"
        raise ValueError(message)
    return value


def _upload_artifact_action(runtime: Mapping[str, JsonValue]) -> str:
    if "upload-artifact-action" not in runtime:
        return DEFAULT_UPLOAD_ARTIFACT_ACTION
    return _runtime_action(runtime["upload-artifact-action"], "upload artifact")


def _validate_permissions(profile: Profile) -> None:
    for permission, access in profile.permissions.items():
        if permission not in PERMISSION_NAMES:
            message = f"unknown GitHub permission: {permission}"
            raise ValueError(message)
        if access not in {"none", "read"}:
            message = f"GitHub execution permission must be none or read: {permission}={access}"
            raise ValueError(message)


def _validate_step(step: Step) -> None:
    if step.uses is not None and ACTION_RE.fullmatch(step.uses) is None:
        message = f"GitHub action must include an explicit ref: {step.uses}"
        raise ValueError(message)
    if step.uses is not None and (step.working_directory is not None or step.shell is not None):
        message = "GitHub uses steps cannot define working-directory or shell"
        raise ValueError(message)


def compile_graph(graph: Graph) -> GeneratedProject:
    """Compile one graph through the public declaration seam."""
    configuration = _validate_github_graph(graph)
    if graph.flows:
        return _compile_flows(graph, configuration)
    projections = {item.event: item for item in _event_projections(graph)}
    manifest = _manifest_value(graph, configuration)
    digest = hashlib.sha256(_canonical_json(manifest).encode()).hexdigest()
    manifest["graphDigest"] = digest
    manifest["_generated"] = GENERATED_NOTICE
    files = (
        GeneratedFile(
            EXECUTION_WORKFLOW,
            _yaml_file(
                _execution_workflow(
                    graph,
                    projections["pull-request"],
                    configuration,
                    digest,
                )
            ),
        ),
        GeneratedFile(
            PUSH_WORKFLOW,
            _yaml_file(
                _execution_workflow(
                    graph,
                    projections["push"],
                    configuration,
                    digest,
                )
            ),
        ),
        GeneratedFile(
            PUBLICATION_WORKFLOW,
            _yaml_file(_publication_workflow(configuration.publisher_action)),
        ),
        GeneratedFile(GRAPH_MANIFEST, _canonical_json(manifest)),
    )
    return GeneratedProject(digest, files)


def _compile_flows(graph: Graph, configuration: _GitHubConfiguration) -> GeneratedProject:
    manifest = _manifest_value(graph, configuration)
    profiles = graph.expanded_profiles()
    manifest.pop("nodes")
    manifest["manifestVersion"] = 1
    manifest["operations"] = {
        operation.id: {
            **_node_value(
                operation.place(
                    FlowNode(operation.id, operation.id),
                    DependencyPolicy.GRAPH,
                ),
                profiles[operation.profile],
            ),
            "diffOnly": operation.diff_only,
        }
        for operation in graph.operations
    }
    manifest["flows"] = {flow.id: _flow_value(flow) for flow in graph.flows}
    for contract in cast("dict[str, dict[str, JsonValue]]", manifest["operations"]).values():
        contract.pop("needs")
    digest = hashlib.sha256(_canonical_json(manifest).encode()).hexdigest()
    manifest.update({"graphDigest": digest, "_generated": GENERATED_NOTICE})
    files: list[GeneratedFile] = []
    for flow in graph.flows:
        if flow.trigger == "workflow-dispatch":
            continue
        projection = EventProjection(flow.trigger, graph.for_flow(flow.id).nodes, flow.dependencies)
        workflow = _execution_workflow(graph, projection, configuration, digest, flow=flow)
        if flow.concurrency is not None:
            workflow["concurrency"] = {
                "group": f"quality-graph-{flow.concurrency}",
                "cancel-in-progress": False,
            }
        if flow.trigger == "push":
            workflow["on"] = {"push": {"branches": list(flow.branches)}}
        else:
            workflow["on"] = {"pull_request": {"branches": [configuration.default_branch]}}
        path = EXECUTION_WORKFLOW if flow.trigger == "pull-request" else PUSH_WORKFLOW
        files.append(GeneratedFile(path, _yaml_file(workflow)))
    if any(flow.presentation == "github-pr" for flow in graph.flows):
        files.append(
            GeneratedFile(
                PUBLICATION_WORKFLOW,
                _yaml_file(_publication_workflow(configuration.publisher_action)),
            )
        )
    files.append(GeneratedFile(GRAPH_MANIFEST, _canonical_json(manifest)))
    paths = {item.path for item in files}
    retired = tuple(
        path
        for path in (EXECUTION_WORKFLOW, PUSH_WORKFLOW, PUBLICATION_WORKFLOW)
        if path not in paths
    )
    return GeneratedProject(digest, tuple(files), retired)


def _flow_value(flow: Flow) -> dict[str, JsonValue]:
    return {
        "trigger": flow.trigger,
        "branches": list(flow.branches),
        "inputs": dict(flow.inputs),
        "dependencies": flow.dependencies.value,
        "presentation": flow.presentation,
        "concurrency": flow.concurrency,
        "execution": "design-only" if flow.trigger == "workflow-dispatch" else "github-actions",
        "nodes": [
            {
                "id": node.id,
                "operation": node.operation,
                "needs": list(node.needs),
                "checkpoint": dict(node.checkpoint),
            }
            for node in flow.nodes
        ],
    }


def _manifest_value(
    graph: Graph,
    configuration: _GitHubConfiguration,
) -> dict[str, JsonValue]:
    profiles = graph.expanded_profiles()
    value: dict[str, JsonValue] = {
        "manifestVersion": 0,
        "graphVersion": graph.version,
        "provider": graph.provider.name,
        "resultSchemaVersion": 0,
        "runtime": {"action": configuration.runtime_action},
        "profiles": {name: _profile_value(profile) for name, profile in profiles.items()},
        "nodes": [_node_value(node, profiles[node.profile]) for node in graph.nodes],
        "labels": _labels_value(graph),
        "administration": {"roles": list(graph.administrator_roles)},
    }
    if "default-branch" in graph.provider.values:
        value["defaultBranch"] = configuration.default_branch
    runtime = cast("dict[str, JsonValue]", graph.provider.values["runtime"])
    if "upload-artifact-action" in runtime:
        cast("dict[str, JsonValue]", value["runtime"])["uploadArtifactAction"] = (
            configuration.upload_artifact_action
        )
    if graph.execution or any(node.events for node in graph.nodes):
        value["execution"] = {
            event: {
                "dependencies": graph.execution.get(event, DependencyPolicy.GRAPH).value,
            }
            for event in SUPPORTED_EVENTS
        }
        effective_events = {node.id: list(node.events or SUPPORTED_EVENTS) for node in graph.nodes}
        for node_value in cast("list[dict[str, JsonValue]]", value["nodes"]):
            node_value["events"] = cast(
                "JsonValue",
                effective_events[cast("str", node_value["id"])],
            )
    return value


def _profile_value(profile: Profile) -> dict[str, JsonValue]:
    value: dict[str, JsonValue] = {
        "runner": profile.runner,
        "setup": [_step_value(step) for step in profile.setup],
        "env": dict(profile.environment),
        "permissions": dict(profile.permissions),
        "services": dict(profile.services),
    }
    _put_optional(value, "timeoutMinutes", profile.timeout_minutes)
    _put_optional(value, "container", profile.container)
    return value


def _node_value(node: Node, profile: Profile) -> dict[str, JsonValue]:
    result_value: dict[str, JsonValue] = {"adapter": node.result.kind.value}
    _put_optional(result_value, "path", node.result.path)
    value: dict[str, JsonValue] = {
        "id": node.id,
        "title": node.title,
        "profile": node.profile,
        "needs": list(node.needs),
        "step": _step_value(node.step),
        "result": result_value,
        "policy": {
            "blocking": node.policy.blocking,
            "blockingSeverities": [severity.value for severity in node.policy.blocking_severities],
            "approvals": {
                "findings": node.policy.approvals.findings,
                "files": node.policy.approvals.files,
                "node": node.policy.approvals.node,
            },
        },
        "env": {**profile.environment, **node.environment},
    }
    _put_optional(value, "timeoutMinutes", node.timeout_minutes or profile.timeout_minutes)
    if isinstance(node.failing_label, LabelSpec):
        value["failingLabel"] = _label_value(node.failing_label)
    elif node.failing_label is False:
        value["failingLabel"] = False
    return value


def _step_value(step: Step) -> dict[str, JsonValue]:
    value: dict[str, JsonValue] = {}
    _put_optional(value, "name", step.name)
    _put_optional(value, "run", step.run)
    _put_optional(value, "uses", step.uses)
    if step.arguments:
        value["with"] = dict(step.arguments)
    if step.environment:
        value["env"] = dict(step.environment)
    _put_optional(value, "working-directory", step.working_directory)
    _put_optional(value, "shell", step.shell)
    return value


def _labels_value(graph: Graph) -> dict[str, JsonValue]:
    value: dict[str, JsonValue] = {"enabled": graph.labels.enabled}
    if graph.labels.failing is not None:
        value["failing"] = _label_value(graph.labels.failing)
    return value


def _label_value(label: LabelSpec) -> dict[str, JsonValue]:
    return {
        "name": label.name,
        "color": label.color.lower(),
        "description": label.description,
        "create": label.create,
    }


def _execution_workflow(
    graph: Graph,
    projection: EventProjection,
    configuration: _GitHubConfiguration,
    digest: str,
    *,
    flow: Flow | None = None,
) -> dict[str, JsonValue]:
    profiles = graph.expanded_profiles()
    jobs: dict[str, JsonValue] = {
        node.id: _execution_job(
            node,
            profiles[node.profile],
            configuration,
            digest,
            flow=flow,
        )
        for node in projection.nodes
    }
    trigger: dict[str, JsonValue]
    name: str
    if projection.event == "pull-request":
        name = "Quality Graph"
        trigger = {
            "pull_request": {"branches": [configuration.default_branch]},
            "workflow_dispatch": {},
        }
    else:
        name = "Quality Graph (push)"
        trigger = {"push": {"branches": [configuration.default_branch]}}
    return {
        "name": name,
        "on": trigger,
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "quality-graph-${{ github.workflow }}-${{ github.ref }}",
            "cancel-in-progress": True,
        },
        "jobs": jobs,
    }


def _execution_job(
    node: Node,
    profile: Profile,
    configuration: _GitHubConfiguration,
    graph_digest: str,
    *,
    flow: Flow | None = None,
) -> dict[str, JsonValue]:
    runner = cast("str", profile.runner)
    command = _workflow_step(node.step)
    command.update(
        {
            "name": f"Run {node.title}",
            "id": "quality-command",
            "continue-on-error": True,
        }
    )
    result_path = f"${{{{ runner.temp }}}}/quality-graph/{node.id}.json"
    collect: dict[str, JsonValue] = {
        "name": f"Collect {node.title} result",
        "id": "quality-result",
        "if": "always()",
        "uses": configuration.runtime_action,
        "with": _collection_inputs(node, graph_digest, flow),
    }
    upload: dict[str, JsonValue] = {
        "name": f"Upload {node.title} result",
        "if": "always()",
        "uses": configuration.upload_artifact_action,
        "with": {
            "name": f"quality-result-{node.id}-${{{{ github.run_attempt }}}}",
            "path": result_path,
            "if-no-files-found": "error",
            "retention-days": 7,
        },
    }
    enforce: dict[str, JsonValue] = {
        "name": f"Enforce {node.title} result",
        "if": "always()",
        "shell": "bash",
        "env": {"EXIT_CODE": "${{ steps.quality-result.outputs.exit-code }}"},
        "run": 'exit "${EXIT_CODE:-2}"',
    }
    value: dict[str, JsonValue] = {
        "name": node.title,
        "runs-on": runner,
        "permissions": dict(profile.permissions),
        "steps": [
            *(_workflow_step(step) for step in profile.setup),
            command,
            collect,
            upload,
            enforce,
        ],
    }
    if node.needs:
        value["needs"] = list(node.needs)
    environment = _json_string_mapping(profile.environment)
    environment.update(_json_string_mapping(node.environment))
    if flow is not None:
        environment.update(
            {
                "QG_FLOW_ID": flow.id,
                "QG_OPERATION_ID": node.operation_id,
                "QG_NODE_ID": node.id,
                "QG_NODE_TITLE": node.title,
                "QG_GRAPH_DIGEST": graph_digest,
            }
        )
    if environment:
        value["env"] = environment
    timeout = node.timeout_minutes or profile.timeout_minutes
    _put_optional(value, "timeout-minutes", timeout)
    _put_optional(value, "container", profile.container)
    if profile.services:
        value["services"] = dict(profile.services)
    return value


def _collection_inputs(node: Node, graph_digest: str, flow: Flow | None) -> dict[str, JsonValue]:
    inputs: dict[str, JsonValue] = {
        "operation": "collect",
        "node-id": node.id,
        "title": node.title,
        "adapter": node.result.kind.value,
        "report-path": node.result.path or "",
        "command-outcome": "${{ steps.quality-command.outcome }}",
        "graph-digest": graph_digest,
        "approval-findings": str(node.policy.approvals.findings).lower(),
        "approval-files": str(node.policy.approvals.files).lower(),
        "approval-node": str(node.policy.approvals.node).lower(),
    }
    if flow is not None:
        inputs.update(
            {
                "flow-id": flow.id,
                "operation-id": node.operation_id,
                "presentation": flow.presentation,
            }
        )
        if flow.presentation != "github-pr":
            inputs.update(
                {"approval-findings": "false", "approval-files": "false", "approval-node": "false"}
            )
    return inputs


def _workflow_step(step: Step) -> dict[str, JsonValue]:
    return _step_value(step)


def _publication_workflow(runtime_action: str) -> dict[str, JsonValue]:
    publish_permissions: dict[str, JsonValue] = {
        "actions": "read",
        "checks": "write",
        "contents": "read",
        "issues": "write",
        "pull-requests": "write",
    }
    publish_job: dict[str, JsonValue] = {
        "name": "Publish Quality Graph",
        "if": (
            "github.event_name == 'workflow_run' "
            "&& github.event.workflow_run.event == 'pull_request'"
        ),
        "runs-on": "ubuntu-latest",
        "permissions": publish_permissions,
        "steps": [
            {
                "name": "Publish trusted Quality Graph state",
                "uses": runtime_action,
                "with": {
                    "operation": (
                        "${{ github.event.action == 'completed' && 'publish' || 'watch' }}"
                    )
                },
            }
        ],
    }
    command_job: dict[str, JsonValue] = {
        "name": "Handle Quality Graph command",
        "if": "github.event_name == 'issue_comment' && github.event.issue.pull_request",
        "runs-on": "ubuntu-latest",
        "permissions": {
            "actions": "write",
            "contents": "read",
            "issues": "write",
            "pull-requests": "write",
        },
        "steps": [
            {
                "name": "Handle trusted Quality Graph command",
                "uses": runtime_action,
                "with": {"operation": "command"},
            }
        ],
    }
    return {
        "name": "Quality Graph Publisher",
        "on": {
            "workflow_run": {
                "workflows": ["Quality Graph"],
                "types": ["requested", "completed"],
            },
            "issue_comment": {"types": ["created", "edited"]},
        },
        "permissions": {},
        "concurrency": {
            "group": (
                "quality-graph-publish-"
                "${{ github.event.workflow_run.id || github.event.issue.number }}"
            ),
            "cancel-in-progress": False,
        },
        "jobs": {"publish": publish_job, "command": command_job},
    }


def _yaml_file(value: Mapping[str, JsonValue]) -> str:
    body = yaml.dump(
        dict(value),
        Dumper=WorkflowDumper,
        default_flow_style=False,
        sort_keys=False,
        width=1_000,
    )
    return GENERATED_HEADER + body


def _canonical_json(value: JsonValue) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _json_string_mapping(value: Mapping[str, str]) -> dict[str, JsonValue]:
    return dict(value)


def _put_optional(target: dict[str, JsonValue], key: str, value: JsonValue) -> None:
    if value is not None:
        target[key] = value
