from __future__ import annotations

import json
from dataclasses import replace

import pytest
import yaml

from qg_github.compiler import compile_graph, event_projection, project_graph
from quality_graph_core.graph import Graph

SOURCE = (
    "version: 0\n"
    "runtime: {action: 'owner/runtime@1111111111111111111111111111111111111111'}\n"
    "profiles: {default: {}}\n"
    "operations: {lint: {run: make lint}, test: {run: make test}}\n"
    "flows:\n"
    "  review:\n"
    "    trigger: pull-request\n"
    "    presentation: github-pr\n"
    "    nodes: {lint: {}, test: {needs: [lint]}}\n"
    "  main:\n"
    "    trigger: {push: {branches: [main]}}\n"
    "    nodes: {lint: {}, test: {needs: [lint]}}\n"
    "  release:\n"
    "    trigger: workflow-dispatch\n"
    "    concurrency: production\n"
    "    presentation: release\n"
    "    nodes:\n"
    "      lint: {}\n"
    "      test:\n"
    "        needs: [lint]\n"
    "        checkpoint: {environment: prestable, observation-seconds: 3600}\n"
)


def test_compile_explicit_flows_separates_execution_and_release_contract() -> None:
    compiled = compile_graph(Graph.from_yaml(SOURCE))
    files = {str(item.path): item.content for item in compiled.files}
    review = yaml.safe_load(files[".github/workflows/quality-graph.yml"])
    main = yaml.safe_load(files[".github/workflows/quality-graph-push.yml"])
    manifest = json.loads(files[".quality-graph/manifest.json"])

    assert review["jobs"]["test"]["needs"] == ["lint"]
    assert "needs" not in main["jobs"]["test"]
    assert "quality-graph-release.yml" not in " ".join(files)
    assert manifest["flows"]["release"]["execution"] == "design-only"
    assert manifest["flows"]["release"]["nodes"][1]["checkpoint"]["observation-seconds"] == 3600
    collect = main["jobs"]["lint"]["steps"][1]["with"]
    assert collect["flow-id"] == "main"
    assert collect["operation-id"] == "lint"
    assert collect["presentation"] == "none"
    assert compile_graph(Graph.from_yaml(SOURCE)) == compiled


def test_explicit_flow_selection_and_named_concurrency() -> None:
    graph = Graph.from_yaml(SOURCE)
    assert event_projection(graph, "push").nodes == graph.for_flow("main").nodes
    assert project_graph(graph, "push").flow_id == "main"
    with pytest.raises(ValueError, match="original declaration"):
        compile_graph(graph.for_flow("release"))
    with pytest.raises(ValueError, match="no flow"):
        project_graph(graph, "missing")
    only_main = replace(graph, flows=(replace(graph.flows[1], concurrency="checks"),))
    files = {str(item.path): item.content for item in compile_graph(only_main).files}
    assert set(files) == {
        ".github/workflows/quality-graph-push.yml",
        ".quality-graph/manifest.json",
    }
    workflow = yaml.safe_load(files[".github/workflows/quality-graph-push.yml"])
    assert workflow["concurrency"] == {"group": "quality-graph-checks", "cancel-in-progress": False}


def test_github_rejects_unsupported_flow_combinations() -> None:
    graph = Graph.from_yaml(SOURCE)
    with pytest.raises(ValueError, match="one pull-request"):
        compile_graph(replace(graph, flows=(*graph.flows, replace(graph.flows[0], id="other"))))
    with pytest.raises(ValueError, match="unique placement titles"):
        compile_graph(
            replace(
                graph, operations=(graph.operations[0], replace(graph.operations[1], title="Lint"))
            )
        )


def test_explicit_manifest_and_workflow_provenance_are_complete() -> None:
    compiled = compile_graph(Graph.from_yaml(SOURCE))
    files = {str(item.path): item.content for item in compiled.files}
    manifest = json.loads(files[".quality-graph/manifest.json"])
    assert manifest["manifestVersion"] == 1
    assert manifest["graphDigest"] == compiled.graph_digest
    assert manifest["_generated"].startswith("Generated by Quality Graph.")
    assert "nodes" not in manifest
    assert manifest["flows"] == {
        "review": {
            "trigger": "pull-request",
            "branches": [],
            "inputs": {},
            "dependencies": "graph",
            "presentation": "github-pr",
            "concurrency": None,
            "execution": "github-actions",
            "nodes": [
                {"id": "lint", "operation": "lint", "needs": [], "checkpoint": {}},
                {"id": "test", "operation": "test", "needs": ["lint"], "checkpoint": {}},
            ],
        },
        "main": {
            "trigger": "push",
            "branches": ["main"],
            "inputs": {},
            "dependencies": "none",
            "presentation": "none",
            "concurrency": None,
            "execution": "github-actions",
            "nodes": [
                {"id": "lint", "operation": "lint", "needs": [], "checkpoint": {}},
                {"id": "test", "operation": "test", "needs": ["lint"], "checkpoint": {}},
            ],
        },
        "release": {
            "trigger": "workflow-dispatch",
            "branches": [],
            "inputs": {},
            "dependencies": "graph",
            "presentation": "release",
            "concurrency": "production",
            "execution": "design-only",
            "nodes": [
                {"id": "lint", "operation": "lint", "needs": [], "checkpoint": {}},
                {
                    "id": "test",
                    "operation": "test",
                    "needs": ["lint"],
                    "checkpoint": {"environment": "prestable", "observation-seconds": 3600},
                },
            ],
        },
    }
    assert manifest["operations"]["lint"] == {
        "id": "lint",
        "title": "Lint",
        "profile": "default",
        "step": {"run": "make lint"},
        "result": {"adapter": "exit-code"},
        "env": {},
        "diffOnly": False,
        "policy": {
            "blocking": True,
            "blockingSeverities": ["error"],
            "approvals": {"findings": True, "files": False, "node": False},
        },
    }
    assert set(manifest["operations"]) == {"lint", "test"}
    assert compiled.retired_files == ()
    for path, flow_id, trigger, presentation in (
        (".github/workflows/quality-graph.yml", "review", "pull_request", "github-pr"),
        (".github/workflows/quality-graph-push.yml", "main", "push", "none"),
    ):
        workflow = yaml.safe_load(files[path])
        assert workflow["on"] == {trigger: {"branches": ["main"]}}
        assert workflow["jobs"]["lint"]["env"] == {
            "QG_FLOW_ID": flow_id,
            "QG_OPERATION_ID": "lint",
            "QG_NODE_ID": "lint",
            "QG_NODE_TITLE": "Lint",
            "QG_GRAPH_DIGEST": compiled.graph_digest,
        }
        inputs = workflow["jobs"]["lint"]["steps"][1]["with"]
        assert inputs == {
            "operation": "collect",
            "node-id": "lint",
            "title": "Lint",
            "adapter": "exit-code",
            "report-path": "",
            "command-outcome": "${{ steps.quality-command.outcome }}",
            "graph-digest": compiled.graph_digest,
            "approval-findings": "true" if presentation == "github-pr" else "false",
            "approval-files": "false",
            "approval-node": "false",
            "flow-id": flow_id,
            "operation-id": "lint",
            "presentation": presentation,
        }
    publisher = yaml.safe_load(files[".github/workflows/quality-graph-publish.yml"])
    assert publisher["on"]["workflow_run"]["workflows"] == ["Quality Graph"]
    assert (
        publisher["jobs"]["publish"]["steps"][0]["uses"]
        == "owner/runtime@1111111111111111111111111111111111111111"
    )


def test_required_check_requires_pr_presentation() -> None:
    graph = Graph.from_yaml(SOURCE)
    with pytest.raises(ValueError, match=r"merge\.required"):
        compile_graph(
            replace(
                graph,
                flows=(graph.flows[1],),
                provider=replace(
                    graph.provider, values={**graph.provider.values, "merge": {"required": True}}
                ),
            )
        )
