import json
from pathlib import Path

import pytest
import yaml
from yamllint.config import YamlLintConfig
from yamllint.linter import run as run_yamllint

from qg_github.compiler import (
    EXECUTION_WORKFLOW,
    GRAPH_MANIFEST,
    PUBLICATION_WORKFLOW,
    compile_graph,
)
from quality_graph_core.graph import Graph
from tests.test_graph import GRAPH, MAXIMAL_GRAPH, RUNTIME


def generated() -> dict[str, str]:
    project = compile_graph(Graph.from_yaml(GRAPH))
    return {str(item.path): item.content for item in project.files}


def workflow(path: object) -> dict[str, object]:
    return yaml.safe_load(generated()[str(path)])


def test_compiler_is_deterministic_and_emits_complete_contract() -> None:
    first = compile_graph(Graph.from_yaml(GRAPH))
    second = compile_graph(Graph.from_yaml(GRAPH))

    assert first == second
    assert [item.path for item in first.files] == [
        EXECUTION_WORKFLOW,
        PUBLICATION_WORKFLOW,
        GRAPH_MANIFEST,
    ]
    assert all(item.content.endswith("\n") for item in first.files)
    assert generated()[str(EXECUTION_WORKFLOW)].startswith("# Generated by Quality Graph")


def test_complete_compiler_output_matches_contract_snapshots() -> None:
    snapshot_root = Path(__file__).parent / "snapshots" / "compiler"

    for path, content in generated().items():
        assert content == (snapshot_root / path).read_text()

    maximal = compile_graph(Graph.from_yaml(MAXIMAL_GRAPH))
    for item in maximal.files:
        assert item.content == (snapshot_root / "maximal" / item.path).read_text()


def test_generated_workflows_pass_standard_yaml_indentation() -> None:
    configuration = YamlLintConfig(
        "{extends: default, rules: {line-length: disable, "
        "truthy: {allowed-values: ['true', 'false', 'on']}}}"
    )

    for path in (EXECUTION_WORKFLOW, PUBLICATION_WORKFLOW):
        problems = list(run_yamllint(generated()[str(path)], configuration, str(path)))
        assert problems == []


def test_manifest_expands_profiles_and_binds_graph_digest() -> None:
    project = compile_graph(Graph.from_yaml(GRAPH))
    manifest = json.loads(generated()[str(GRAPH_MANIFEST)])

    assert manifest["graphDigest"] == project.graph_digest
    assert len(project.graph_digest) == 64
    assert manifest["profiles"]["python"]["setup"][0]["uses"] == "actions/checkout@v7"
    assert manifest["nodes"][1]["result"] == {
        "adapter": "sarif",
        "path": "reports/lint.sarif",
    }
    assert manifest["nodes"][1]["failingLabel"]["name"] == "quality:lint"
    assert manifest["labels"]["failing"]["name"] == "quality:failed"


def test_execution_workflow_preserves_native_jobs_and_dependencies() -> None:
    value = workflow(EXECUTION_WORKFLOW)
    jobs = value["jobs"]
    lint = jobs["lint"]

    assert value["permissions"] == {"contents": "read"}
    assert set(value["on"]) == {"pull_request", "push", "workflow_dispatch"}
    assert list(jobs) == ["format", "lint"]
    assert lint["needs"] == ["format"]
    assert lint["runs-on"] == "ubuntu-latest"
    assert lint["permissions"] == {"contents": "read"}
    assert lint["env"] == {"UV_NO_SYNC": "1"}
    assert lint["steps"][2]["continue-on-error"] is True
    assert lint["steps"][3]["with"]["adapter"] == "sarif"
    assert lint["steps"][4]["uses"] == "actions/upload-artifact@v7"
    assert lint["steps"][4]["with"]["retention-days"] == 7
    assert lint["steps"][5]["run"] == 'exit "${EXIT_CODE:-2}"'


def test_publication_workflow_is_privileged_without_untrusted_checkout() -> None:
    value = workflow(PUBLICATION_WORKFLOW)
    publish = value["jobs"]["publish"]
    command = value["jobs"]["command"]
    serialized = generated()[str(PUBLICATION_WORKFLOW)]

    assert value["permissions"] == {}
    assert value["on"]["workflow_run"]["types"] == ["requested", "completed"]
    assert publish["steps"][0]["with"]["operation"].endswith("'publish' || 'watch' }}")
    assert publish["permissions"]["actions"] == "read"
    assert publish["permissions"]["pull-requests"] == "write"
    assert publish["permissions"]["checks"] == "write"
    assert command["permissions"]["pull-requests"] == "write"
    assert publish["if"].endswith("workflow_run.event == 'pull_request'")
    assert command["permissions"]["actions"] == "write"
    assert "actions/checkout" not in serialized
    assert "pull_request_target" not in serialized


def test_publisher_runtime_can_roll_forward_without_changing_execution_provenance() -> None:
    publisher = "alchemmist/quality-graph@" + "b" * 40
    source = GRAPH.replace(
        f"      action: {RUNTIME}",
        f"      action: {RUNTIME}\n      publisher-action: {publisher}",
    )
    original = compile_graph(Graph.from_yaml(GRAPH))
    updated = compile_graph(Graph.from_yaml(source))
    files = {str(item.path): item.content for item in updated.files}

    assert original.graph_digest == updated.graph_digest
    assert publisher in files[str(PUBLICATION_WORKFLOW)]
    assert publisher not in files[str(EXECUTION_WORKFLOW)]


def test_compiler_preserves_optional_step_job_and_label_fields() -> None:
    configured_label = "label:\n      name: quality:lint\n      color: ff0000\n      create: true"
    source = GRAPH.replace(configured_label, "label: false")
    source = source.replace(
        'persist-credentials: "false"',
        'persist-credentials: "false"\n        env:\n          SETUP_MODE: safe',
    )
    source = source.replace(
        "runner: ubuntu-latest",
        "runner: ubuntu-latest\n    container: python:3.12\n"
        "    services:\n      redis:\n        image: redis:7",
    )
    project = compile_graph(Graph.from_yaml(source))
    files = {str(item.path): item.content for item in project.files}
    execution = yaml.safe_load(files[str(EXECUTION_WORKFLOW)])
    manifest = json.loads(files[str(GRAPH_MANIFEST)])

    assert manifest["nodes"][1]["failingLabel"] is False
    assert execution["jobs"]["format"]["steps"][0]["env"] == {"SETUP_MODE": "safe"}
    assert execution["jobs"]["format"]["container"] == "python:3.12"
    assert execution["jobs"]["format"]["services"]["redis"]["image"] == "redis:7"


@pytest.mark.parametrize(
    ("source", "message"),
    [
        (GRAPH.replace("actions/checkout@v7", "local-action", 1), "explicit ref"),
        (
            GRAPH.replace(
                "runner: ubuntu-latest",
                "runner: ubuntu-latest\n    permissions:\n      issues: write",
            ),
            "none or read",
        ),
        (
            GRAPH.replace(
                "runner: ubuntu-latest",
                "runner: ubuntu-latest\n    permissions:\n      unknown: read",
            ),
            "unknown GitHub permission",
        ),
        (GRAPH.replace(RUNTIME, "alchemmist/quality-graph@main"), "40-character-commit"),
        (
            GRAPH.replace(
                f"      action: {RUNTIME}",
                f"      action: {RUNTIME}\n      publisher-action: mutable",
            ),
            "publisher action",
        ),
        (GRAPH.replace("name: github", "name: gitlab"), "cannot compile provider"),
        (GRAPH.replace("title: Lint", "title: Formatting"), "unique node titles"),
        (
            GRAPH.replace("    runtime:\n", "    unknown: true\n    runtime:\n"),
            "unknown configuration",
        ),
        (
            GRAPH.replace(
                f"  configuration:\n    runtime:\n      action: {RUNTIME}\n",
                "  configuration: {}\n",
            ),
            "requires a runtime object",
        ),
        (
            GRAPH.replace(
                f"      action: {RUNTIME}",
                f"      action: {RUNTIME}\n      unknown: true",
            ),
            "runtime contains unknown fields",
        ),
        (
            GRAPH.replace(
                "uses: actions/checkout@v7",
                "uses: actions/checkout@v7\n        working-directory: src",
                1,
            ),
            "cannot define",
        ),
    ],
)
def test_github_provider_rejects_platform_specific_invalid_configuration(
    source: str,
    message: str,
) -> None:
    with pytest.raises((TypeError, ValueError), match=message):
        compile_graph(Graph.from_yaml(source))
