import json

import yaml

from quality_graph.compiler import (
    EXECUTION_WORKFLOW,
    GRAPH_MANIFEST,
    PUBLICATION_WORKFLOW,
    compile_graph,
)
from quality_graph.graph import Graph
from tests.test_graph import GRAPH


def generated() -> dict[str, str]:
    project = compile_graph(Graph.from_yaml(GRAPH))
    return {str(item.path): item.content for item in project.files}


def workflow(path: object) -> dict[str, object]:
    return yaml.safe_load(generated()[str(path)])


def test_compiler_is_deterministic_and_emits_complete_contract() -> None:
    first = compile_graph(Graph.from_yaml(GRAPH))
    second = compile_graph(Graph.from_yaml(GRAPH))

    assert first == second
    assert [item.path for item in first.files] == [
        EXECUTION_WORKFLOW,
        PUBLICATION_WORKFLOW,
        GRAPH_MANIFEST,
    ]
    assert all(item.content.endswith("\n") for item in first.files)
    assert generated()[str(EXECUTION_WORKFLOW)].startswith("# Generated by Quality Graph")


def test_manifest_expands_profiles_and_binds_graph_digest() -> None:
    project = compile_graph(Graph.from_yaml(GRAPH))
    manifest = json.loads(generated()[str(GRAPH_MANIFEST)])

    assert manifest["graphDigest"] == project.graph_digest
    assert len(project.graph_digest) == 64
    assert manifest["profiles"]["python"]["setup"][0]["uses"] == "actions/checkout@v7"
    assert manifest["nodes"][1]["result"] == {
        "adapter": "sarif",
        "path": "reports/lint.sarif",
    }
    assert manifest["nodes"][1]["failingLabel"]["name"] == "quality:lint"
    assert manifest["labels"]["failing"]["name"] == "quality:failed"


def test_execution_workflow_preserves_native_jobs_and_dependencies() -> None:
    value = workflow(EXECUTION_WORKFLOW)
    jobs = value["jobs"]
    lint = jobs["lint"]

    assert value["permissions"] == {"contents": "read"}
    assert set(value["on"]) == {"pull_request", "push", "workflow_dispatch"}
    assert list(jobs) == ["format", "lint"]
    assert lint["needs"] == ["format"]
    assert lint["runs-on"] == "ubuntu-latest"
    assert lint["permissions"] == {"contents": "read"}
    assert lint["env"] == {"UV_NO_SYNC": "1"}
    assert lint["steps"][2]["continue-on-error"] is True
    assert lint["steps"][3]["with"]["adapter"] == "sarif"
    assert lint["steps"][4]["uses"] == "actions/upload-artifact@v7"
    assert lint["steps"][4]["with"]["retention-days"] == 7
    assert lint["steps"][5]["run"] == 'exit "${EXIT_CODE:-2}"'


def test_publication_workflow_is_privileged_without_untrusted_checkout() -> None:
    value = workflow(PUBLICATION_WORKFLOW)
    publish = value["jobs"]["publish"]
    command = value["jobs"]["command"]
    serialized = generated()[str(PUBLICATION_WORKFLOW)]

    assert value["permissions"] == {}
    assert value["on"]["workflow_run"]["types"] == ["requested", "in_progress", "completed"]
    assert publish["permissions"]["actions"] == "read"
    assert publish["permissions"]["checks"] == "write"
    assert command["permissions"]["actions"] == "write"
    assert "actions/checkout" not in serialized
    assert "pull_request_target" not in serialized


def test_compiler_preserves_optional_step_job_and_label_fields() -> None:
    configured_label = "label:\n      name: quality:lint\n      color: ff0000\n      create: true"
    source = GRAPH.replace(configured_label, "label: false")
    source = source.replace(
        'persist-credentials: "false"',
        'persist-credentials: "false"\n        env:\n          SETUP_MODE: safe',
    )
    source = source.replace(
        "runner: ubuntu-latest",
        "runner: ubuntu-latest\n    container: python:3.12\n"
        "    services:\n      redis:\n        image: redis:7",
    )
    project = compile_graph(Graph.from_yaml(source))
    files = {str(item.path): item.content for item in project.files}
    execution = yaml.safe_load(files[str(EXECUTION_WORKFLOW)])
    manifest = json.loads(files[str(GRAPH_MANIFEST)])

    assert manifest["nodes"][1]["failingLabel"] is False
    assert execution["jobs"]["format"]["steps"][0]["env"] == {"SETUP_MODE": "safe"}
    assert execution["jobs"]["format"]["container"] == "python:3.12"
    assert execution["jobs"]["format"]["services"]["redis"]["image"] == "redis:7"
