"""Compile declared checks into deterministic native GitLab pipelines."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, replace
from importlib.metadata import version
from pathlib import PurePosixPath
from typing import TYPE_CHECKING

import yaml

from qg_gitlab.api import integer, server_url, string
from quality_graph_core.graph import DependencyPolicy, Graph
from quality_graph_core.provider import GeneratedFile, GeneratedProject

if TYPE_CHECKING:
    from quality_graph_core.graph import Node, Profile
    from quality_graph_core.result import JsonValue

RUNTIME_VERSION = version("quality-graph-gitlab")
GENERATED_HEADER = "# Generated by Quality Graph. DO NOT EDIT MANUALLY.\n"
QUALITY_EXIT_CODE = 10
DEFAULT_IMAGE = "python:3.12-slim"
INSTALL_RUNTIME = (
    f"python -m pip install --disable-pip-version-check quality-graph-gitlab=={RUNTIME_VERSION}"
)


def configuration(graph: Graph) -> dict[str, JsonValue]:
    """Validate GitLab settings independently of every other provider."""
    if graph.provider.name != "gitlab":
        message = f"GitLab cannot compile provider {graph.provider.name}"
        raise ValueError(message)
    values = dict(graph.provider.values)
    unknown = values.keys() - {
        "default-branch",
        "server-url",
        "api-url",
        "runtime-version",
        "runner-tags",
        "publisher-user-id",
        "publisher-tags",
        "image",
    }
    if unknown:
        message = f"unknown GitLab configuration: {', '.join(sorted(unknown))}"
        raise ValueError(message)
    branch = string(values.get("default-branch", "main"), "default branch")
    if any(character in branch for character in ('"', "\\", "\n", "\r", "$")):
        message = "GitLab default branch contains unsupported expression characters"
        raise ValueError(message)
    values["default-branch"] = branch
    values["server-url"] = server_url(
        string(values.get("server-url", "https://gitlab.com"), "server URL")
    )
    if "api-url" in values:
        values["api-url"] = server_url(string(values["api-url"], "API URL"))
    runtime = string(values.get("runtime-version", RUNTIME_VERSION), "runtime version")
    if runtime != RUNTIME_VERSION:
        message = "GitLab runtime version must match the installed provider version"
        raise ValueError(message)
    values["runtime-version"] = runtime
    if "publisher-user-id" in values:
        integer(values["publisher-user-id"], "publisher user ID")
    for name, default in (("runner-tags", ["qg-execution"]), ("publisher-tags", ["qg-publisher"])):
        tags = values.get(name, default)
        if (
            not isinstance(tags, list)
            or not tags
            or any(not isinstance(tag, str) or not tag for tag in tags)
        ):
            message = f"{name} must be a nonempty string array"
            raise ValueError(message)
        values[name] = [string(tag, name) for tag in tags]
    values["image"] = string(values.get("image", DEFAULT_IMAGE), "execution image")
    return values


def execution_graphs(graph: Graph) -> tuple[tuple[str, str, Graph], ...]:
    """Project the supported MR and push executions with explicit membership."""
    if graph.flows:
        result: list[tuple[str, str, Graph]] = []
        events: set[str] = set()
        for flow in graph.flows:
            if flow.is_release:
                if flow.execution == "design-only":
                    continue
                message = "GitLab executable release flows are not supported"
                raise ValueError(message)
            if flow.trigger not in {"pull-request", "push"} or flow.trigger in events:
                message = "GitLab supports at most one MR flow and one branch flow"
                raise ValueError(message)
            if flow.presentation not in {"none", "gitlab-mr"}:
                message = "GitLab flows require none or gitlab-mr presentation"
                raise ValueError(message)
            events.add(flow.trigger)
            result.append((flow.id, flow.trigger, graph.for_flow(flow.id)))
        return tuple(result)
    result = []
    for event, flow_id in (("pull-request", "mr"), ("push", "push")):
        selected = tuple(node for node in graph.nodes if not node.events or event in node.events)
        membership = {node.id for node in selected}
        dependencies = graph.execution.get(event, DependencyPolicy.GRAPH)
        selected = tuple(
            replace(
                node,
                needs=tuple(need for need in node.needs if need in membership)
                if dependencies is DependencyPolicy.GRAPH
                else (),
            )
            for node in selected
        )
        if selected:
            result.append((flow_id, event, replace(graph, nodes=selected)))
    return tuple(result)


def job_name(flow_id: str, node_id: str) -> str:
    """Return the compiler-owned stable native job name."""
    return f"qg:{flow_id}:{node_id}"


def graph_digest(graph: Graph) -> str:
    """Bind execution and policy to a canonical complete declaration."""
    encoded = json.dumps(asdict(graph), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode()).hexdigest()


def _validate_node(node: Node, profile: Profile) -> None:
    for step in (*profile.setup, *(node.steps or (node.step,))):
        if step.uses is not None or step.arguments:
            message = "GitLab steps must use repository commands, not GitHub Actions"
            raise ValueError(message)
        if step.shell not in {None, "sh", "bash"}:
            message = "GitLab steps support sh or bash"
            raise ValueError(message)
    if node.deployment_environment or node.permissions is not None or profile.services:
        message = (
            "GitLab quality jobs do not accept deployment permissions or service escape hatches"
        )
        raise ValueError(message)
    if profile.permissions not in ({}, {"contents": "read"}):
        message = "GitHub permissions cannot be applied to GitLab quality jobs"
        raise ValueError(message)
    if profile.runner not in {None, "ubuntu-latest"}:
        message = "Configure GitLab runner-tags instead of a GitHub profile runner"
        raise ValueError(message)


def _execution_job(
    node: Node, profile: Profile, flow_id: str, event: str, rule: str
) -> dict[str, JsonValue]:
    """Render one native execution job with its failure policy."""
    item: dict[str, JsonValue] = {
        "stage": "quality",
        "rules": [{"if": rule}],
        "needs": [job_name(flow_id, need) for need in node.needs],
        "script": [f"qg-gitlab execute --flow {flow_id} --node {node.id}"],
        "artifacts": {
            "when": "always",
            "paths": [f".qg/results/{flow_id}/{node.id}.json"],
            "expire_in": "7 days",
        },
        "interruptible": True,
    }
    if profile.container:
        item["image"] = profile.container
    timeout = node.timeout_minutes or profile.timeout_minutes
    if timeout:
        item["timeout"] = f"{timeout} minutes"
    environment = {**profile.environment, **node.environment}
    if environment:
        item["variables"] = dict(environment)
    if event == "pull-request":
        item["allow_failure"] = {"exit_codes": [QUALITY_EXIT_CODE]}
    elif not node.policy.blocking:
        item["allow_failure"] = True
    return item


def compile_graph(graph: Graph) -> GeneratedProject:
    """Generate CI, its execution manifest and a trusted publisher template."""
    settings = configuration(graph)
    digest = graph_digest(graph)
    profiles = graph.expanded_profiles()
    flows = execution_graphs(graph)
    workflow: dict[str, JsonValue] = {
        "workflow": {
            "rules": [
                {"if": '$CI_PIPELINE_SOURCE == "merge_request_event"'},
                {
                    "if": (
                        '$CI_PIPELINE_SOURCE == "push" && '
                        "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
                    ),
                    "when": "never",
                },
                {"if": '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'},
                {"when": "never"},
            ]
        },
        "stages": ["quality"],
        "default": {
            "image": settings["image"],
            "tags": settings["runner-tags"],
            "before_script": [INSTALL_RUNTIME],
        },
    }
    manifests: list[JsonValue] = []
    for flow_id, event, projected in flows:
        rule = (
            '$CI_PIPELINE_SOURCE == "merge_request_event"'
            if event == "pull-request"
            else '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
        )
        if graph.flows and event == "push":
            declared = next(flow for flow in graph.flows if flow.id == flow_id)
            if declared.branches:
                choices = " || ".join(
                    f"$CI_COMMIT_BRANCH == {json.dumps(branch)}" for branch in declared.branches
                )
                rule = f"({rule}) && ({choices})"
        for node in projected.nodes:
            profile = profiles[node.profile]
            _validate_node(node, profile)
            identifier = job_name(flow_id, node.id)
            workflow[identifier] = _execution_job(node, profile, flow_id, event, rule)
        if event == "pull-request":
            workflow[f"qg:{flow_id}:admission"] = {
                "stage": "quality",
                "rules": [{"if": rule}],
                "needs": [],
                "script": [f"qg-gitlab gate --flow {flow_id}"],
                "timeout": "5 minutes",
            }
        manifests.append(
            {
                "id": flow_id,
                "event": event,
                "nodes": [
                    {
                        "id": node.id,
                        "job": job_name(flow_id, node.id),
                        "operation": node.operation_id,
                    }
                    for node in projected.nodes
                ],
            }
        )
    manifest: dict[str, JsonValue] = {"version": 1, "graphDigest": digest, "flows": manifests}
    publisher: dict[str, JsonValue] = {
        "workflow": {
            "rules": [
                {
                    "if": (
                        '$CI_COMMIT_REF_PROTECTED == "true" && ('
                        '$CI_PIPELINE_SOURCE == "trigger" || '
                        '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web")'
                    )
                },
                {"when": "never"},
            ]
        },
        "publish": {
            "image": DEFAULT_IMAGE,
            "tags": settings["publisher-tags"],
            "variables": {"GIT_STRATEGY": "none"},
            "resource_group": "quality-graph-publication",
            "before_script": [INSTALL_RUNTIME],
            "script": ["qg-gitlab publish"],
            "timeout": "10 minutes",
        },
    }
    files = (
        GeneratedFile(
            PurePosixPath(".gitlab-ci.yml"),
            GENERATED_HEADER + yaml.safe_dump(workflow, sort_keys=False, width=100),
        ),
        GeneratedFile(
            PurePosixPath(".qg/gitlab.json"), json.dumps(manifest, indent=2, sort_keys=True) + "\n"
        ),
        GeneratedFile(
            PurePosixPath(".qg/gitlab-publisher.yml"),
            GENERATED_HEADER + yaml.safe_dump(publisher, sort_keys=False, width=100),
        ),
    )
    return GeneratedProject(digest, files)


def starter(default_branch: str) -> str:
    """Create a provider-native starter without requiring GitHub Actions."""
    value: dict[str, JsonValue] = {
        "version": 0,
        "provider": {
            "name": "gitlab",
            "configuration": {
                "default-branch": default_branch,
                "server-url": "https://gitlab.com",
                "runtime-version": RUNTIME_VERSION,
            },
        },
        "profiles": {"default": {"container": DEFAULT_IMAGE}},
        "administration": {"roles": ["maintain", "admin"]},
        "nodes": {"quality": {"title": "Quality", "run": "make check"}},
    }
    return yaml.safe_dump(value, sort_keys=False)
