"""Find public GitHub repositories that use Quality Graph."""

from __future__ import annotations

import argparse
import http.client
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from textwrap import shorten
from typing import Protocol, TypedDict, cast
from urllib.parse import quote, urlencode

from tabulate import tabulate

DEFAULT_ADOPTERS = Path("docs/adopters.json")
HTTP_ERROR_STATUS = 400
RESULTS_PER_PAGE = 100
SEARCHES = {
    "action": '"alchemmist/quality-graph@" in:file',
    "generated workflow": '"Generated by Quality Graph" "qg generate" in:file',
}


class SearchRepository(TypedDict):
    """Describe the repository fragment in a code search result."""

    full_name: str


class SearchItem(TypedDict):
    """Describe one GitHub code search result."""

    repository: SearchRepository


class SearchResponse(TypedDict):
    """Describe one page returned by GitHub code search."""

    incomplete_results: bool
    items: list[SearchItem]


class RepositoryResponse(TypedDict):
    """Describe repository metadata used in the ranking."""

    archived: bool
    description: str | None
    fork: bool
    full_name: str
    html_url: str
    stargazers_count: int


class AdopterRecord(TypedDict):
    """Describe the catalog fields needed by discovery."""

    name: str
    repository: str
    logo: str


class AdopterCatalog(TypedDict):
    """Describe the checked-in adopter catalog."""

    projects: list[AdopterRecord]


class GitHubApi(Protocol):
    """Describe the GitHub operations used by discovery."""

    def search_code(self, query: str, max_pages: int) -> tuple[SearchItem, ...]:
        """Return code search matches for one strong signature."""

    def repository(self, full_name: str) -> RepositoryResponse:
        """Return metadata for one repository."""


@dataclass(frozen=True)
class Candidate:
    """Carry one verified public repository and its discovery evidence."""

    full_name: str
    url: str
    stars: int
    description: str
    evidence: tuple[str, ...]
    listed: bool


class GitHubClient:
    """Expose the small GitHub REST surface needed by adopter discovery."""

    def __init__(self, token: str) -> None:
        """Configure authenticated requests without exposing the token."""
        self._headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "quality-graph-adopter-discovery",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    def search_code(self, query: str, max_pages: int) -> tuple[SearchItem, ...]:
        """Return up to max_pages of code matches for one strong signature."""
        matches: list[SearchItem] = []
        for page in range(1, max_pages + 1):
            parameters = urlencode({"q": query, "per_page": RESULTS_PER_PAGE, "page": page})
            response = cast("SearchResponse", self._get(f"/search/code?{parameters}"))
            matches.extend(response["items"])
            if response["incomplete_results"]:
                message = "GitHub returned incomplete code search results; retry later"
                raise RuntimeError(message)
            if len(response["items"]) < RESULTS_PER_PAGE:
                break
        return tuple(matches)

    def repository(self, full_name: str) -> RepositoryResponse:
        """Return popularity and lifecycle metadata for one repository."""
        path = f"/repos/{quote(full_name, safe='/')}"
        return cast("RepositoryResponse", self._get(path))

    def _get(self, path: str) -> SearchResponse | RepositoryResponse:
        connection = http.client.HTTPSConnection("api.github.com", timeout=30)
        try:
            connection.request("GET", path, headers=self._headers)
            response = connection.getresponse()
            if response.status >= HTTP_ERROR_STATUS:
                message = f"HTTP {response.status} {response.reason}"
                raise RuntimeError(message)
            return cast("SearchResponse | RepositoryResponse", json.loads(response.read()))
        except (http.client.HTTPException, OSError) as error:
            message = f"GitHub API request failed: {error}"
            raise RuntimeError(message) from error
        finally:
            connection.close()


def listed_repositories(path: Path) -> frozenset[str]:
    """Return normalized repository names already present in the ticker."""
    catalog = cast("AdopterCatalog", json.loads(path.read_text()))
    return frozenset(project["repository"].lower() for project in catalog["projects"])


def discover(
    client: GitHubApi,
    listed: frozenset[str],
    *,
    max_pages: int,
) -> tuple[Candidate, ...]:
    """Search, verify, and rank active non-fork repositories by stars."""
    evidence_by_repository: dict[str, set[str]] = {}
    names: dict[str, str] = {}
    for evidence, query in SEARCHES.items():
        for item in client.search_code(query, max_pages):
            full_name = item["repository"]["full_name"]
            normalized = full_name.lower()
            names[normalized] = full_name
            evidence_by_repository.setdefault(normalized, set()).add(evidence)

    candidates: list[Candidate] = []
    for normalized, full_name in sorted(names.items()):
        repository = client.repository(full_name)
        if repository["fork"] or repository["archived"]:
            continue
        candidates.append(
            Candidate(
                full_name=repository["full_name"],
                url=repository["html_url"],
                stars=repository["stargazers_count"],
                description=repository["description"] or "",
                evidence=tuple(sorted(evidence_by_repository[normalized])),
                listed=normalized in listed,
            ),
        )
    return tuple(sorted(candidates, key=lambda item: (-item.stars, item.full_name.lower())))


def render_table(candidates: tuple[Candidate, ...]) -> str:
    """Render candidates as an aligned ASCII table."""
    rows = [
        (
            rank,
            candidate.full_name,
            f"{candidate.stars:,}",
            "listed" if candidate.listed else "new",
            ", ".join(candidate.evidence),
            shorten(candidate.description, width=64, placeholder="…") or "—",
        )
        for rank, candidate in enumerate(candidates, 1)
    ]
    return (
        tabulate(
            rows,
            headers=("#", "Project", "Stars", "Status", "Evidence", "Description"),
            tablefmt="grid",
            colalign=("right", "left", "right", "left", "left", "left"),
            disable_numparse=True,
        )
        + "\n"
    )


def main() -> int:
    """Find and print ranked Quality Graph adopter candidates."""
    parser = argparse.ArgumentParser(
        description="Find public Quality Graph adopters and rank them by GitHub stars.",
    )
    parser.add_argument("--adopters", type=Path, default=DEFAULT_ADOPTERS)
    parser.add_argument("--max-pages", type=int, choices=range(1, 11), default=1)
    parser.add_argument("--new-only", action="store_true")
    arguments = parser.parse_args()
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        parser.error("GITHUB_TOKEN is required for GitHub code search")

    try:
        candidates = discover(
            GitHubClient(token),
            listed_repositories(arguments.adopters),
            max_pages=arguments.max_pages,
        )
    except FileNotFoundError:
        parser.error(f"adopter catalog does not exist: {arguments.adopters}")
    except RuntimeError as error:
        sys.stderr.write(f"GitHub search failed: {error}\n")
        return 1

    if arguments.new_only:
        candidates = tuple(candidate for candidate in candidates if not candidate.listed)
    if not candidates:
        sys.stdout.write("No matching repositories found.\n")
        return 0
    sys.stdout.write(render_table(candidates))
    return 0


if __name__ == "__main__":
    sys.exit(main())
