---
name: Build release candidate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --locked --all-groups
      - run: make package
      - uses: actions/upload-artifact@v7
        with:
          name: distributions
          path: dist/*
          if-no-files-found: error
